//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.Movie_Actors = new HashSet<Movie_Actors>();
        }
    
        public int IdActor { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Movie_Actors> Movie_Actors { get; set; }
    }
}
