//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Movie_Country = new HashSet<Movie_Country>();
        }
    
        public int IdCountry { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Movie_Country> Movie_Country { get; set; }
    }
}
