//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        public Director()
        {
            this.Movie_Director = new HashSet<Movie_Director>();
        }
    
        public int IdDirectors { get; set; }
        public string nameDirector { get; set; }
    
        public virtual ICollection<Movie_Director> Movie_Director { get; set; }
    }
}
