//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Movies_Genres = new HashSet<Movies_Genres>();
        }
    
        public int IdGenre { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Movies_Genres> Movies_Genres { get; set; }
    }
}
