//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieUser_TypeStorage
    {
        public int IdRelMovieUser_TypeStorage { get; set; }
        public int idRelMovieUser { get; set; }
        public int idTypeStorage { get; set; }
    
        public virtual Movie_Users Movie_Users { get; set; }
        public virtual TypeStorage TypeStorage { get; set; }
    }
}
