//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DATABASE_MOVIESHELFEntities1 : DbContext
    {
        public DATABASE_MOVIESHELFEntities1()
            : base("name=DATABASE_MOVIESHELFEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actor> Actors { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Director> Directors { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Movie_Actors> Movie_Actors { get; set; }
        public DbSet<Movie_Country> Movie_Country { get; set; }
        public DbSet<Movie_Director> Movie_Director { get; set; }
        public DbSet<Movie_Users> Movie_Users { get; set; }
        public DbSet<Movies_Genres> Movies_Genres { get; set; }
        public DbSet<Movies1> Movies1 { get; set; }
        public DbSet<MovieUser_TypeStorage> MovieUser_TypeStorage { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TypeStorage> TypeStorages { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
