//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Actors
    {
        public int IdMovie_Actor { get; set; }
        public int idActor { get; set; }
        public int idMovie { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movies1 Movies1 { get; set; }
    }
}
