//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Users
    {
        public Movie_Users()
        {
            this.MovieUser_TypeStorage = new HashSet<MovieUser_TypeStorage>();
        }
    
        public int IdRelMovie_User { get; set; }
        public int idUser { get; set; }
        public int idMovie { get; set; }
        public Nullable<bool> Seen { get; set; }
        public Nullable<bool> Favorite { get; set; }
        public Nullable<int> PersonalScore { get; set; }
    
        public virtual Movies1 Movies1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<MovieUser_TypeStorage> MovieUser_TypeStorage { get; set; }
    }
}
