//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOVIESHELF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Movie_Users = new HashSet<Movie_Users>();
        }
    
        public int IdUsers { get; set; }
        public string Username { get; set; }
        public string email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Movie_Users> Movie_Users { get; set; }
    }
}
